### ISSUE TITLE
High false positive rate for secrets.patterns=[A-Z0-9]{20}

### ISSUE THREAD

**Issue by matthewdeanmartin** [awslabs/git-secrets#38]
Twenty upper case characters happen all the time- in data files, in binaries, everywhere. Removing this rule is remarkably difficult, requiring reading the source code and then formulating a regex that matches [A-Z0-9]{20} (see git-config man for what I was reading on unsetting a value with a repeated key name https://schacon.github.io/git/git-config.html)

My team is responding to these challenges by uninstalling it or using the no-verify.

I think this is a very bad default, or if it is a good default, the difficultly level for turning it off is too high.

**Comment by mtdowling** [comment]
git-secrets shouldn't scan binary files, so that shouldn't be an issue. This pattern does match SHA-1 hashes, so I agree that it does have a high false positive rate. I'm hesitant to remove this regex now, at least without a major version bump; while it is chatty, it does prevent things like AWS access keys from being committed.

I thought that removing patterns from git-secrets is pretty simple: all you need to do is edit your `.git/config` file and remove the patterns you don't like under the `[secrets]` section. For example, in this case, you would remove the line `patterns = [A-Z0-9]{20}`.

For a more automated method for removing a pattern, what would you think about adding the ability to remove a pattern to git-secrets from the command line?

**Comment by bramswenson** [comment]
This pattern will match tons of JS files for various reasons such as embedded image data.

**Comment by bramswenson** [comment]
:+1: for more secret pattern management interfaces on the cli.

**Comment by bramswenson** [comment]
Having to write a regex to prevent false positive is also a show stopper. Think about the embedded images in JS pattern.

**Comment by rodom** [comment]
!57 might help with this

**Comment by mtdowling** [comment]
Closed by #89
